name: CI

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]

env:
  GO_VERSION: 1.22
  CGO_ENABLED: 0

jobs:
  build-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [linux, darwin, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set output
        id: set_output
        run: |
          if [ ${{ matrix.os }} = "windows" ]; then
              echo "exe=coredns-${{ matrix.os }}-${{ matrix.arch }}.exe" >> $GITHUB_OUTPUT
          else
              echo "exe=coredns-${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binary
        run: |
          git clone https://github.com/coredns/coredns.git
          ln -s `pwd` coredns/plugin/
          cd coredns
          echo 'mysql:github.com/snail2sky/coredns_mysql_extend' >> plugin.cfg
          go generate && go get
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          export CGO_ENABLED=${{ env.CGO_ENABLED }}
          go build -o ${{ steps.set_output.outputs.exe }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 
          files: |
            ${{ steps.set_output.outputs.exe }}
